[package]
name = "rust-http"
version = "0.1.0"
edition = "2024"

[dependencies]
signal-hook = "0.3.18"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "net", "io-util", "macros"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
