[package]
name = "rust-http"
version = "0.1.0"
edition = "2024"

[dependencies]
pin-project-lite = "0.2.16"
signal-hook = "0.3.18"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
